---
title: "inter-rater"
output: html_document
---
```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(stringr)
library(boot)
library(purrr)
library(ggplot2)
library(ggthemes)
library(feather)
library(poweRlaw)
library(wordbankr)
#library(rwebppl)
library(lme4)
library(Hmisc)
library(qdapRegex)
library(HDInterval)
library(lmerTest)
library(childesr)
library(brms)
library(stringr)

library(xlsx)
library(irr)

library(readr)
library(cowplot)

```


```{r}
### dara For Theophile
###################

Theophile <-  read_csv("Annotations-final/Annotation_csv_speaker/Theophile_020020.csv") %>%
  mutate(child = "Theophile",
         age = 2,
         file = "020020") %>%
  
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Theophile_020208.csv") %>%
  mutate(child = "Theophile",
         age = 2,
         file = "020208")) %>%
  
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Theophile_030200.csv") %>%
  mutate(child = "Theophile",
         age = 3,
         file = "030200")) %>%
  
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Theophile_030410.csv") %>%
  mutate(child = "Theophile",
         age = 3,
         file = "030410")) %>%
  
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Theophile_040329.csv") %>%
  mutate(child = "Theophile",
         age = 4,
         file = "040329")) %>%
  
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Theophile_040620.csv") %>%
  mutate(child = "Theophile",
         age = 4,
         file = "040620")) 


### dara For Madeleine
######################

Madeleine <-  read_csv("Annotations-final/Annotation_csv_speaker/Madeleine_020102.csv") %>%
  mutate(child = "Madeleine",
         age = 2,
         file = "020102") %>%
  
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Madeleine_020206.csv") %>%
  mutate(child = "Madeleine",
         age = 2,
         file = "020206")) %>%
  
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Madeleine_030028.csv") %>%
  mutate(child = "Madeleine",
         age = 3,
         file = "030028")) %>%
  
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Madeleine_030302.csv") %>%
  mutate(child = "Madeleine",
         age = 3,
         file = "030302")) %>%
  
   bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Madeleine_041003.csv") %>%
  mutate(child = "Madeleine",
         age = 4,
         file = "041003")) %>%
  
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Madeleine_050105.csv") %>%
  mutate(child = "Madeleine",
         age = 4,
         file = "050105"))
  
  
### dara For Adrien
######################

Adrien_020222  <-  read_csv("Annotations-final/Annotation_csv_speaker/Adrien_020222.csv") %>%
  mutate(child = "Adrien",
         age = 2,
         file = "020222")
  
Adrien_020328 <-  read_csv("Annotations-final/Annotation_csv_speaker/Adrien_020328_CHI.csv") %>%
  mutate(child = "Adrien",
         age = 2,
         file = "020328") %>%
  filter(`list-ID` == 1) %>%
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Adrien_020328_PAR.csv") %>%
  mutate(child = "Adrien",
         age = 2,
         file = "020328") %>%
    filter(`list-ID` == 2)) 


Adrien_030015 <-  read_csv("Annotations-final/Annotation_csv_speaker/Adrien_030015_CHI.csv") %>%
  mutate(child = "Adrien",
         age = 3,
         file = "030015") %>%
  filter(`list-ID` == 1) %>%
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Adrien_030015_PAR.csv") %>%
  mutate(child = "Adrien",
         age = 3,
         file = "030015") %>%
    filter(`list-ID` == 2)) 


Adrien_030212 <-  read_csv("Annotations-final/Annotation_csv_speaker/Adrien_030212_CHI.csv") %>%
  mutate(child = "Adrien",
         age = 3,
         file = "030212") %>%
  filter(`list-ID` == 1) %>%
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Adrien_030212_PAR.csv") %>%
  mutate(child = "Adrien",
         age = 3,
         file = "030212") %>%
    filter(`list-ID` == 2)) 


Adrien_030909 <-  read_csv("Annotations-final/Annotation_csv_speaker/Adrien_030909_CHI.csv") %>%
  mutate(child = "Adrien",
         age = 4,
         file = "030909") %>%
  filter(`list-ID` == 1) %>%
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Adrien_030909_PAR.csv") %>%
  mutate(child = "Adrien",
         age = 4,
         file = "030909") %>%
    filter(`list-ID` == 2)) 


Adrien_031113 <-  read_csv("Annotations-final/Annotation_csv_speaker/Adrien_031113_CHI.csv") %>%
  mutate(child = "Adrien",
         age = 4,
         file = "031113") %>%
  filter(`list-ID` == 1) %>%
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Adrien_031113_PAR.csv") %>%
  mutate(child = "Adrien",
         age = 4,
         file = "031113") %>%
    filter(`list-ID` == 2)) 

Adrien <- Adrien_020222 %>%
  bind_rows(Adrien_020328) %>%
  bind_rows(Adrien_030015) %>%
  bind_rows(Adrien_030212) %>%
  bind_rows(Adrien_030909) %>%
  bind_rows(Adrien_031113) 


### dara For Anae
##################

Anae_020025 <-  read_csv("Annotations-final/Annotation_csv_speaker/Anae_020025_CHI.csv") %>%
  mutate(child = "Anae",
         age = 2,
         file = "020025") %>%
  filter(`list-ID` == 1) %>%
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Anae_020025_PAR.csv") %>%
  mutate(child = "Anae",
         age = 2,
         file = "020025") %>%
    filter(`list-ID` == 2)) 


Anae_020105 <-  read_csv("Annotations-final/Annotation_csv_speaker/Anae_020105_CHI.csv") %>%
  mutate(child = "Anae",
         age = 2,
         file = "020105") %>%
  filter(`list-ID` == 1) %>%
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Anae_020105_PAR.csv") %>%
  mutate(child = "Anae",
         age = 2,
         file = "020105") %>%
    filter(`list-ID` == 2)) 

Anae_021122  <-  read_csv("Annotations-final/Annotation_csv_speaker/Anae_021122.csv") %>%
  mutate(child = "Anae",
         age = 3,
         file = "021122")

Anae_030522 <-  read_csv("Annotations-final/Annotation_csv_speaker/Anae_030522_CHI.csv") %>%
  mutate(child = "Anae",
         age = 3,
         file = "030522") %>%
  filter(`list-ID` == 1) %>%
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Anae_030522_PAR.csv") %>%
  mutate(child = "Anae",
         age = 3,
         file = "030522") %>%
    filter(`list-ID` == 2))

Anae_031000 <-  read_csv("Annotations-final/Annotation_csv_speaker/Anae_031000_CHI.csv") %>%
  mutate(child = "Anae",
         age = 4,
         file = "031000") %>%
  filter(`list-ID` == 1) %>%
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Anae_031000_PAR.csv") %>%
  mutate(child = "Anae",
         age = 4,
         file = "031000") %>%
    filter(`list-ID` == 2))

Anae_040012  <-  read_csv("Annotations-final/Annotation_csv_speaker/Anae_040012.csv") %>%
  mutate(child = "Anae",
         age = 4,
         file = "040012")

Anae_040523 <-  read_csv("Annotations-final/Annotation_csv_speaker/Anae_040523_CHI.csv") %>%
  mutate(child = "Anae",
         age = 4,
         file = "040523") %>%
  filter(`list-ID` == 1) %>%
  bind_rows(read_csv("Annotations-final/Annotation_csv_speaker/Anae_040523_PAR.csv") %>%
  mutate(child = "Anae",
         age = 4,
         file = "040523") %>%
    filter(`list-ID` == 2))


Anae <- Anae_020025 %>%
  bind_rows(Anae_020105) %>%
  bind_rows(Anae_021122) %>%
  bind_rows(Anae_030522) %>%
  bind_rows(Anae_031000) %>%
  bind_rows(Anae_040012) %>%
  bind_rows(Anae_040523) 


###ALL DATA:

data <- Anae %>%
  bind_rows(Adrien) %>%
  bind_rows(Madeleine) %>%
  bind_rows(Theophile)


#Date
convertDate  <- function(dateString) {
  y = as.numeric(substr(dateString, 1, 2))
  m = as.numeric(substr(dateString, 3, 4))
  d = as.numeric(substr(dateString, 5, 6))
  mydate <- y*365 + m *30 + d
  mydate <- round(mydate/365,1)
  return(mydate)
}
```


```{r}
#numner of turns by speaker by file
data_age <-  data %>%
  rename(listID = `list-ID`) %>%
  rowwise() %>%
  mutate(age2 = convertDate(file)) %>%
  mutate(Role = if_else(Speaker =='FAT' | Speaker =='MOT', 'PAR', if_else(Speaker =='CHI', 'CHI', 'OTHER')))

data_turns_sum <- data_age %>%
  filter(listID == 1) %>% # turns are duplicated in list1 and list2
  group_by(child, Role, age2, file) %>%
  summarise(Turns_sum = n()) %>%
  ungroup() 

data_turns_sum$Role = factor(data_turns_sum$Role, levels = c("CHI", "PAR", "OTHER"))
```

```{r}

ggplot(data_turns_sum,  aes(age2, Turns_sum, col= Role))+
   geom_point(size=2 ,alpha= 0.3)+
  geom_smooth(method = lm, se = T, alpha=0.15,aes(fill=Role))+
   theme_few()+
  theme(aspect.ratio = 0.7, 
        axis.text.x=element_text(size=15),
        axis.text.y=element_text(size=15),
        strip.text.x = element_text(size=15),
        strip.text.y = element_text(size=15),
        axis.title=element_text(size=15),
        legend.title = element_blank(),
        legend.position="bottom"
        
        )  +
  xlab("Child age (years)") +ylab("Turns per transcript")

```

```{r}
#Models about number of turns per year 
model_turn_chi <- lmer(formula = Turns_avg ~ age2  +  (1 | child), 
             data =data_turns_sum %>% filter(Role == "CHI"))

model_turn_par <- lmer(formula = Turns_avg ~ age2  +  (1 | child), 
             data =data_turns_sum %>% filter(Role == "PAR"))

model_turn_other <- lmer(formula = Turns_avg ~ age2  +  (1 | child), 
             data =data_turns_sum %>% filter(Role == "OTHER"))


summary(model_turn_chi)
summary(model_turn_par)
summary(model_turn_other)
```

Process data 
```{r}
# Here process annotation 

data_processed <- data_age %>%
  filter(annotation != "[NULL,NULL,NULL]") %>%
  rowwise() %>% 
  mutate(lab1 = str_remove(str_remove(unlist(strsplit(annotation, ',')),"\\["), "]")[1], 
         lab2 = str_remove(str_remove(unlist(strsplit(annotation, ',')),"\\["), "]")[2],
         lab3 = str_remove(str_remove(unlist(strsplit(annotation, ',')),"\\["), "]")[3]
         ) %>%
  #ungroup() %>%
  #here make each lable in separate line
  gather(label_number, label_full, lab1, lab2, lab3) %>%
  rowwise() %>% 
  mutate(label = unlist(strsplit(label_full, ':'))[1],
         label_type = unlist(strsplit(label_full, ':'))[2] ,
         label_subtype = unlist(strsplit(label_full, ':'))[3]
         ) %>%
  mutate(Role_annot = unlist(strsplit(label, '-'))[1]) %>%
  select(-label_full, -annotation) %>%
  filter(label != 'NULL')
```

Child-initiation
```{r}
##Dependency measures: F->R for chidlren 

##First put data in the right format
child <- data_processed %>%
  filter(label =='CHI-Initiation' | label =='PAR-Response' | label =='CHI-Follow-up') %>%
  mutate(RoleID = if_else(label =='CHI-Initiation', 1, 
                 if_else(label =='PAR-Response', 2, 3))) %>%
  group_by(child, file) %>%
  arrange(ID, .by_group = TRUE) %>%
  ungroup()

#this removes label successive dupplicates (quesion followed with another question)
child <- child[cumsum(rle(as.character(child$label))$lengths), ]

#this rkeeps only the QRF sequences (this is to remive cases when annotators forgot to annoatate the whole sequence), we lose only 15 datapoints over around 1200 in total)
child <- child %>%
 mutate(unit = row_number() %in% ((grepRaw("1,2,3",
                            paste0(c(0, RoleID, 0), collapse = ","),
                            all = TRUE,
                            fixed = TRUE) - 1) / 2)) %>%
 group_by(unit = cumsum(unit)) %>%
 filter(unit != 0) %>% 
 slice(1:3) 
  
child <- child %>%
  select(child, age2, file, label, label_type, unit) %>%
  spread(label, label_type)
  
#now categories into

child_dep <- child %>%
  mutate(Response = if_else(`PAR-Response` == "No-response" | `PAR-Response` == "No-label" | `PAR-Response` == "Non-answer", "No-response", "Response")) %>%
  mutate(Feedback = if_else(`CHI-Follow-up` == "No-followup" | `CHI-Follow-up` == "other" | `CHI-Follow-up` == "Otherwise" | `CHI-Follow-up` == "laugh", "No-Followup", "Followup")) %>%
  group_by(age2, file, Response, Feedback) %>%
  summarise(n =n()) %>%
  spread(Feedback, n) %>%
  mutate(value = 100* `Followup` /(`Followup` + `No-Followup`)) %>%
  #mutate(sample = `Followup` + `No-Followup`) %>%
  select(-`Followup`, -`No-Followup`) %>%
  #spread(Response, value) %>%
  #mutate(feedback = `Response` - `No-response`)%>%
  #select(-`Response`, -`No-response`) %>%
  mutate(Role = "Child")


ggplot(child_dep,  aes(child, feedback))+
   geom_point(size=2 ,alpha= 0.3)+
  #geom_smooth(method = lm, se = T, alpha=0.15)+
   theme_few()+
  theme(aspect.ratio = 0.7, 
        axis.text.x=element_text(size=15),
        axis.text.y=element_text(size=15),
        strip.text.x = element_text(size=15),
        strip.text.y = element_text(size=15),
        axis.title=element_text(size=15),
        legend.title = element_blank(),
        legend.position="bottom"
        
        )  +
  xlab("Child age (years)") +ylab("Turns per transcript")

###Caregiver 

caregiver <- data_processed %>%
  filter(label =='PAR-Initiation' | label =='CHI-Response' | label =='PAR-Follow-up') %>%
  mutate(RoleID = if_else(label =='PAR-Initiation', 1, 
                 if_else(label =='CHI-Response', 2, 3))) %>%
  group_by(child, file) %>%
  arrange(ID, .by_group = TRUE) %>%
  ungroup()

caregiver <- caregiver[cumsum(rle(as.character(caregiver$label))$lengths), ]

#this rkeeps only the QRF sequences (this is to remive cases when annotators forgot to annoatate the whole sequence), we lose only 15 datapoints over around 1200 in total)
caregiver <- caregiver %>%
 mutate(unit = row_number() %in% ((grepRaw("1,2,3",
                            paste0(c(0, RoleID, 0), collapse = ","),
                            all = TRUE,
                            fixed = TRUE) - 1) / 2)) %>%
 group_by(unit = cumsum(unit)) %>%
 filter(unit != 0) %>% 
 slice(1:3) 
  
caregiver <- caregiver %>%
  select(child, age2, file, label, label_type, unit) %>%
  spread(label, label_type)
  
caregiver_dep <- caregiver %>%
  mutate(Response = if_else(`CHI-Response` == "No-response" | `CHI-Response` == "No-label" | `CHI-Response` == "Non-answer", "No-response", "Response")) %>%
  mutate(Feedback = if_else(`PAR-Follow-up` == "No-followup" | `PAR-Follow-up` == "other" | `PAR-Follow-up` == "Otherwise" | `PAR-Follow-up` == "laugh", "No-Followup", "Followup")) %>%
  group_by(age2, file, Response, Feedback) %>%
  summarise(n =n()) %>%
  spread(Feedback, n) %>%
  mutate(value = 100* `Followup` /(`Followup` + `No-Followup`)) %>%
  #mutate(sample = `Followup` + `No-Followup`) %>%
  select(-`Followup`, -`No-Followup`) %>%
  spread(Response, value) %>%
  mutate(feedback = `Response` - `No-response`) %>%
 select(-`Response`, -`No-response`) %>%
  mutate(Role = "Cargiver")

all_dep <- child_dep %>%
  bind_rows(caregiver_dep)
  
  
ggplot(all_dep,  aes(age2, feedback, col=Role))+
   geom_point(size=2 ,alpha= 0.3)+
  geom_smooth(method = lm, se = T, alpha=0.15, aes(fill=Role))+
  geom_hline(yintercept=0, linetype="dashed", 
                color = "black", size=1)+
   theme_few()+
  theme(aspect.ratio = 0.7, 
        axis.text.x=element_text(size=15),
        axis.text.y=element_text(size=15),
        strip.text.x = element_text(size=15),
        strip.text.y = element_text(size=15),
        axis.title=element_text(size=15),
        legend.title = element_blank(),
        legend.position="bottom"
        
        )  +
  xlab("Child age (years)") +ylab("Turns per transcript")

summary(lm(feedback ~ age2, data=all_dep %>% filter(Role=="Cargiver")))

```

```{r}

child_dep <- child %>%
  mutate(Response = if_else(`PAR-Response` == "No-response" | `PAR-Response` == "No-label" | `PAR-Response` == "Non-answer", "No-response", "Response")) %>%
  mutate(Feedback = if_else(`CHI-Follow-up` == "No-followup" | `CHI-Follow-up` == "other" | `CHI-Follow-up` == "Otherwise" | `CHI-Follow-up` == "laugh", 0, 1)) %>%
  select(-`CHI-Follow-up`, -`CHI-Initiation`, -`PAR-Response`) %>%
  mutate(Role = "Child")

caregiver_dep <- caregiver %>%
  mutate(Response = if_else(`CHI-Response` == "No-response" | `CHI-Response` == "No-label" | `CHI-Response` == "Non-answer", "No-response", "Response")) %>%
  mutate(Feedback = if_else(`PAR-Follow-up` == "No-followup" | `PAR-Follow-up` == "other" | `PAR-Follow-up` == "Otherwise" | `PAR-Follow-up` == "laugh", 0, 1)) %>%
  select(-`CHI-Response`, -`PAR-Follow-up`, -`PAR-Initiation`) %>%
  mutate(Role = "Caregiver")

all_dep <- child_dep %>%
  bind_rows(caregiver_dep)

ggplot(all_dep,  aes(Response, Feedback))+
  stat_summary(fun.y=mean,position=position_dodge(width=1),geom="bar", fill ="grey")+
  stat_summary(fun.data=mean_cl_normal,position=position_dodge(width=1),geom="pointrange",size=0.5) + 
  #geom_point(position=position_dodge(width=1), size = 2, alpha = 0.3) +
  #stat_summary(fun.data = mean_cl_normal, geom="pointrange", size=0.2, aes(group = Role))+
  #geom_smooth(method = lm, se = FALSE)+
  theme_few()+
  theme(aspect.ratio = 0.7, 
        axis.text.x=element_text(size=17),
        axis.text.y=element_text(size=15),
        strip.text.x = element_text(size=15),
        strip.text.y = element_text(size=15),
        axis.title=element_text(size=20),
        legend.title = element_blank(),
           plot.title = element_text(size=20, face="bold",hjust = 0.5)
        )  +
  ggtitle("Follow-up by Children")+
      
  xlab("Follow-up type") +ylab("Type per follow-up") +
  facet_grid(child~Role, scales= "free_y")



summary(glmer(Feedback ~ Response * age2 + (1|child), data = child_dep, family = binomial))
summary(glmer(Feedback ~ Response * age2 + (1|child), data = caregiver_dep, family = binomial))


#summary(glm(Feedback ~ Response * age2 , data = child_dep, family = binomial))

```

Eexrtact info about Questions, responses, and followups
```{r}
responses <- data_processed %>%
  filter(Role != "OTHER") %>%
  filter(label == 'CHI-Response' | label == 'PAR-Response') %>%
  select(ID, child, Role_annot, age2, file,label, label_type) %>% 
  dplyr::rename(Role = Role_annot) %>%
  mutate(contingency = if_else(label_type == "No-response" | label_type == "No-label" | label_type == "Non-answer", 0, 1)) %>%
  select(-label, -label_type) %>%
  mutate(type = "response")
  
followups <- data_processed %>%
  filter(Role != "OTHER") %>%
  filter(label == 'CHI-Follow-up' | label == 'PAR-Follow-up') %>%
  select(ID, child, Role_annot, age2, file,label,label_type) %>% 
  dplyr::rename(Role = Role_annot) %>%
  mutate(contingency = if_else(label_type == "No-followup" | label_type == "other" | label_type == "Otherwise" |label_type == "laugh", 0, 1)) %>%
  select(-label, -label_type) %>%
  mutate(type = "feedback")

contingency_all <- responses %>%
  bind_rows(followups)
  
contingency_all$type = factor(contingency_all$type, levels = c("response", "feedback"))

ggplot(contingency_all,  aes(age2, contingency, col=Role))+
  #geom_point(size=1 ,alpha= 0.3)+
  geom_smooth(method = lm, se = T, alpha=0.15,aes(fill=Role))+
   theme_few()+
  theme(aspect.ratio = 0.7, 
        axis.text.x=element_text(size=10),
        axis.text.y=element_text(size=10),
        strip.text.x = element_text(size=10),
        strip.text.y = element_text(size=10),
        axis.title=element_text(size=10),
        legend.title = element_blank()#,
        #legend.position="bottom"
        
        )  +
  xlab("Child age (years)") +ylab("% given opportunity")  +
  facet_grid(child~type)

```

Eexrtact info about Questions, responses, and followups
```{r}

questions<- data_processed %>%
  #filter(Role != "OTHER") %>%
  filter(label == 'CHI-Initiation' | label == 'PAR-Initiation') %>%
  group_by(child, Role_annot, age2, file) %>% 
  summarise(quest_per_file = n()) %>%
  ungroup() %>%
  dplyr::rename(Role = Role_annot) %>%
  left_join(data_turns_sum %>% filter(Role != "OTHER")) %>%
  mutate(Questions  = quest_per_file/Turns_sum) %>%
  select(-quest_per_file, -Turns_sum)
  #gather(measure, value,  quest_per_file, quest_per_turn)

responses <- data_processed %>%
  filter(Role != "OTHER") %>%
  filter(label == 'CHI-Response' | label == 'PAR-Response') %>%
  group_by(child, Role_annot, age2, file,label, label_type) %>% 
  summarise(res_per_file = n()) %>%
  ungroup() %>%
  dplyr::rename(Role = Role_annot) %>%
  mutate(res_broad = if_else(label_type == "No-response" | label_type == "No-label" | label_type == "Non-answer", "No-response", "Response")) %>%
  group_by(child, Role, age2, file, res_broad) %>%
  summarise(value_res_broad = sum(res_per_file)) %>%
  #select(-label_type) %>%
  spread(res_broad, value_res_broad)

responses[is.na(responses)] <- 0
responses <-responses %>%
  mutate(all_responses =  `No-response` + Response)%>%
  mutate(Responses = Response / all_responses) %>%
  select(-Response, -`No-response`, -all_responses)


followups <- data_processed %>%
  filter(Role != "OTHER") %>%
  filter(label == 'CHI-Follow-up' | label == 'PAR-Follow-up') %>%
  group_by(child, Role_annot, age2, file,label,label_type) %>% 
  summarise(follow_per_file = n()) %>%
  ungroup() %>%
  dplyr::rename(Role = Role_annot) %>%
  mutate(Follow_broad = if_else(label_type == "No-followup" | label_type == "other" | label_type == "Otherwise" |label_type == "laugh", "No-Followup", "Followup")) %>% # this decision has to be discussed with Morgane and Charlie
  group_by(child, Role, age2, file, Follow_broad) %>%
  summarise(value_follow_broad = sum(follow_per_file)) %>%
  ungroup() %>%
  spread(Follow_broad, value_follow_broad)

followups[is.na(followups)] <- 0
followups <- followups %>%
  mutate(all_followups =  `No-Followup` + Followup)%>%
  mutate(Followups = Followup / all_followups) %>%
  select(-Followup, -`No-Followup`, -all_followups)

QRF_combined <- questions %>%
  full_join(responses) %>%
  full_join(followups)
  
QRF_combined[is.na(QRF_combined)] <- 0

QRF_combined <- QRF_combined %>%
  gather(key, value, Questions:Followups)

QRF_combined$key = factor(QRF_combined$key, levels = c("Questions", "Responses", "Followups"))

```


```{r}


ggplot(QRF_combined,  aes(age2, value, col=Role))+
  geom_point(size=1 ,alpha= 0.3)+
  geom_smooth(method = lm, se = T, alpha=0.15,aes(fill=Role))+
   theme_few()+
  theme(aspect.ratio = 0.7, 
        axis.text.x=element_text(size=10),
        axis.text.y=element_text(size=10),
        strip.text.x = element_text(size=10),
        strip.text.y = element_text(size=10),
        axis.title=element_text(size=10),
        legend.title = element_blank()#,
        #legend.position="bottom"
        
        )  +
  xlab("Child age (years)") +ylab("% given opportunity")  +
  facet_wrap(~key)

```
Question categoris 
```{r}
question_types <- data_processed %>%
  filter(Role != "OTHER") %>%
  filter(label == 'CHI-Initiation' | label == 'PAR-Initiation') %>%
  mutate(type = if_else(!is.na(label_subtype),label_subtype, label_type)) %>%  
  mutate(type= if_else(type == "explanation-based" | type == "explanation-seeking" , "explanation", type)) %>%
  mutate(type= if_else(type == "fact-based " | type == "fact-based" , "fact", type)) %>%
  mutate(type= if_else(type == "fact" | type == "explanation", type, "other")) %>%
  group_by(child, Role_annot, age2, file, type) %>%
  summarise(quest_type = n()) %>%
  ungroup() %>%
  dplyr::rename(Role = Role_annot) %>%
  group_by(child, Role, age2, file) %>%
  mutate(type_per_total = quest_type/sum(quest_type)) %>%
  select(-quest_type) 

question_types <- question_types %>%
  spread(type, type_per_total)
question_types[is.na(question_types)] <- 0

question_types <- question_types %>%
  gather(type, value, explanation:other)

question_types <- question_types %>%
  spread(Role, value)
question_types[is.na(question_types)] <- 0

question_types <- question_types %>%
  gather(Role, value, CHI,PAR)

question_types$type = factor(question_types$type, levels = c("fact", "explanation", "other"))
question_types$Role = factor(question_types$Role, levels = c("PAR", "CHI"))

 
  #facet_grid(.~Role, scales= "free_y")

#question_types %>% filter(quest_per_file > 1)  %>%
#  filter(Role == "CHI") %>%
 # filter(type == "explanation-based")


```

Responses types 
```{r}
response_types <- data_processed %>%
  filter(Role != "OTHER") %>%
  filter(label == 'CHI-Response' | label == 'PAR-Response') %>%
  filter(!(label_type %in% c('Non-answer','No-label', 'No-response'))) %>%
  mutate(type = if_else(label_subtype == "no-explanation-needed", "short", 
                        if_else(label_subtype == "with-explanation-low-quality" | label_subtype == "with-explanation-high-quality", "explanation",label_subtype))) %>%
  group_by(child, Role_annot, age2, file, type) %>%
  summarise(res_type = n()) %>%
  ungroup() %>%
  dplyr::rename(Role = Role_annot) %>%
  group_by(child, Role, age2, file) %>%
  mutate(value = res_type/sum(res_type)) %>%
  select(-res_type) 

response_types <- response_types %>%
  spread(type, value)
response_types[is.na(response_types)] <- 0

response_types <- response_types %>%
  gather(type, value, explanation:short)

response_types <- response_types %>%
  spread(Role, value)
response_types[is.na(response_types)] <- 0

response_types <- response_types %>%
  gather(Role, value, CHI,PAR)


response_types$type = factor(response_types$type, levels = c("short", "explanation", "non-verbal"))
response_types$Role = factor(response_types$Role, levels = c("PAR", "CHI"))






```

```{r}

 followup_types <- data_processed %>%
  filter(Role != "OTHER") %>%
  filter(label == 'CHI-Follow-up' | label == 'PAR-Follow-up') %>%
  filter(!(label_type %in% c('No-followup','other', 'Otherwise','laugh'))) %>%
  mutate(type = if_else(label_type %in% c("Followup-question", "Re-ask-initial-question"), "question",
                   if_else(label_type %in% c("Signal-agreement", "Signal-disagreement",  "Repeat-answer"), "evaluation", 
                      if_else(label_type %in% c("Give-response", "Add-info",  "Own-explanation"), "response", label_type)))) %>%
  group_by(child, Role_annot, age2, file, type) %>%
  summarise(fol_type = n()) %>%
  ungroup() %>%
  dplyr::rename(Role = Role_annot) %>%
  group_by(child, Role, age2, file) %>%
  mutate(value = fol_type/sum(fol_type)) %>%
  select(-fol_type) 

followup_types <- followup_types %>%
  spread(type, value)
followup_types[is.na(followup_types)] <- 0

followup_types <- followup_types %>%
  gather(type, value, evaluation:response)

followup_types <- followup_types %>%
  spread(Role, value)
followup_types[is.na(followup_types)] <- 0

followup_types <- followup_types %>%
  gather(Role, value, CHI,PAR)


#response_types$type = factor(response_types$type, levels = c("short", "explanation", "non-verbal"))
response_types$Role = factor(response_types$Role, levels = c("PAR", "CHI"))



```

```{r}

ggplot(question_types %>% filter(Role=="PAR"),  aes(age2, value, col= type))+
   geom_point(size=2 ,alpha= 0.3)+
  geom_smooth(method = lm, se = T, alpha=0.15,aes(fill=type))+
   theme_few()+
  theme(aspect.ratio = 0.7, 
        axis.text.x=element_text(size=15),
        axis.text.y=element_text(size=15),
        strip.text.x = element_text(size=15),
        strip.text.y = element_text(size=15),
        axis.title=element_text(size=15),
        legend.title = element_blank(),
        legend.text = element_text(size=15),
        legend.position="bottom",
        plot.title = element_text(size=20, face="bold",hjust = 0.5)
        )  +
  ggtitle("Question by Caregivers")+
  ylim(0, 1)+
  xlab("Child age (years)") +ylab("Type per question")

ggplot(response_types %>% filter(Role=="CHI"),  aes(age2, value, col= type))+
   geom_point(size=2 ,alpha= 0.3)+
  geom_smooth(method = lm, se = T, alpha=0.15,aes(fill=type))+
   theme_few()+
  theme(aspect.ratio = 0.7, 
        axis.text.x=element_text(size=15),
        axis.text.y=element_text(size=15),
        strip.text.x = element_text(size=15),
        strip.text.y = element_text(size=15),
        axis.title=element_text(size=15),
        legend.title = element_blank(),
        legend.text = element_text(size=15),
        legend.position="bottom",
        plot.title = element_text(size=20, face="bold",hjust = 0.5)
        )  +
  ggtitle("Response by Children")+
  ylim(-0.12, 1)+
  xlab("Child age (years)") +ylab("Type per response")


ggplot(followup_types %>% filter(Role=="PAR"),  aes(age2, value, col= type))+
   geom_point(size=2 ,alpha= 0.3)+
  geom_smooth(method = lm, se = T, alpha=0.15,aes(fill=type))+
   theme_few()+
  theme(aspect.ratio = 0.7, 
        axis.text.x=element_text(size=15),
        axis.text.y=element_text(size=15),
        strip.text.x = element_text(size=15),
        strip.text.y = element_text(size=15),
        axis.title=element_text(size=15),
        legend.title = element_blank(),
        legend.text = element_text(size=15),
        legend.position="bottom",
        plot.title = element_text(size=20, face="bold",hjust = 0.5)
        )  +
  ggtitle("Follow-up by Caregivers")+
  ylim(0, 1)+
  xlab("Child age (years)") +ylab("Type per follow-up")

```

```{r}

ggplot(question_types %>% filter(Role=="CHI"),  aes(type, value))+
  stat_summary(fun.y=mean,position=position_dodge(width=1),geom="bar",  fill ="grey")+
  #stat_summary(fun.data=mean_cl_normal,position=position_dodge(width=1),geom="pointrange",size=0.5,  aes(group = Role)) + 
  geom_point(position=position_dodge(width=1), size = 2, alpha = 0.3) +
  #stat_summary(fun.data = mean_cl_normal, geom="pointrange", size=0.2, aes(group = Role))+
  #geom_smooth(method = lm, se = FALSE)+
  theme_few()+
  theme(aspect.ratio = 0.7, 
        axis.text.x=element_text(size=17,angle=0),
        axis.text.y=element_text(size=15),
        strip.text.x = element_text(size=15),
        strip.text.y = element_text(size=15),
        axis.title=element_text(size=20),
        legend.title = element_blank(),
          plot.title = element_text(size=20, face="bold",hjust = 0.5)
        )  +
  ggtitle("Question by Children")+
    
  xlab("Question type") +ylab("Type per question")

ggplot(response_types %>% filter(Role=="PAR"),  aes(type, value))+
  stat_summary(fun.y=mean,position=position_dodge(width=1),geom="bar",  fill ="grey")+
  #stat_summary(fun.data=mean_cl_normal,position=position_dodge(width=1),geom="pointrange",size=0.5,  aes(group = Role)) + 
  geom_point(position=position_dodge(width=1), size = 2, alpha = 0.3) +
  #stat_summary(fun.data = mean_cl_normal, geom="pointrange", size=0.2, aes(group = Role))+
  #geom_smooth(method = lm, se = FALSE)+
  theme_few()+
  theme(aspect.ratio = 0.7, 
        axis.text.x=element_text(size=17,angle=0),
        axis.text.y=element_text(size=15),
        strip.text.x = element_text(size=15),
        strip.text.y = element_text(size=15),
        axis.title=element_text(size=20),
        legend.title = element_blank(),
           plot.title = element_text(size=20, face="bold",hjust = 0.5)
        )  +
  ggtitle("Response by Caregiver")+
        
  xlab("Response type") +ylab("Type per response") 
  #facet_grid(.~Role, scales= "free_y")

ggplot(followup_types %>% filter(Role=="CHI"),  aes(type, value))+
  stat_summary(fun.y=mean,position=position_dodge(width=1),geom="bar", fill ="grey")+
  #stat_summary(fun.data=mean_cl_normal,position=position_dodge(width=1),geom="pointrange",size=0.5,  aes(group = Role)) + 
  geom_point(position=position_dodge(width=1), size = 2, alpha = 0.3) +
  #stat_summary(fun.data = mean_cl_normal, geom="pointrange", size=0.2, aes(group = Role))+
  #geom_smooth(method = lm, se = FALSE)+
  theme_few()+
  theme(aspect.ratio = 0.7, 
        axis.text.x=element_text(size=17),
        axis.text.y=element_text(size=15),
        strip.text.x = element_text(size=15),
        strip.text.y = element_text(size=15),
        axis.title=element_text(size=20),
        legend.title = element_blank(),
           plot.title = element_text(size=20, face="bold",hjust = 0.5)
        )  +
  ggtitle("Follow-up by Children")+
      
  xlab("Follow-up type") +ylab("Type per follow-up") 
  #facet_grid(.~Role, scales= "free_y")

```


